services:
    frontend-web:
        build: FrontendWeb
        ports:
            - "5173:5173"
        volumes:
            - ./FrontendWeb:/app

    backend:
        build: Backend
        ports:
            - "3000:3000"
        volumes:
            - ./Backend:/app
    
    mobile-app:
        build:
            context: ./FrontendApp