services:
  frontend-web:
    build: FrontendWeb
    ports:
      - "3000:5173"
    volumes:
      - ./FrontendWeb:/app
    command: npm run dev

  backend:
    build: Backend
    ports:
      - "3001:3001"
    volumes:
      - ./Backend:/app
    command: npm run dev
