volumes:
    area_volume:

services:
    client_web:
        build: FrontendWeb
        ports:
            - "8081:8081"
        volumes:
            - area_volume:/app/public/
        depends_on:
            - server
            - client_mobile

    server:
        build: Backend
        ports:
            - "8080:8080"
        volumes:
            - area_volume:/output

    client_mobile:
        build: FrontendApp
        volumes:
            - area_volume:/output

    service:
        build: Service
        volumes:
            - area_volume:/output