volumes:
    area_volume:

services:
    frontend-web:
        build: FrontendWeb
        ports:
            - "8081:8081"
        volumes:
            - area_volume:/output

    backend:
        build: Backend
        ports:
            - "8080:8080"
        volumes:
            - area_volume:/output

    mobile_app:
        build: FrontendApp
        volumes:
            - area_volume:/output