name: Backend

on:
    push:
        branches-ignore:
            - "ga-ignore-*"

jobs:
    backend-compile-test:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v4
            - name: NodeJS Setup
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install node_modules
              run: |
                  cd Backend/
                  npm i
            - name: Build
              run: |
                  cd Backend/
                  npm run build
    backend-testing:
        name: run test
        runs-on: ubuntu-latest
        needs: backend-compile-test
        steps:
            - name: Checkout
              uses: actions/Checkout@v4
            - name: NodeJS Setup
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install node_modules
              run: |
                  cd Backend/
                  npm i
            - name: Create .env file
              run: |
                cd Backend/
                echo "${{secrets.ENV_FILE}}" > .env
            - name: Run units tests
              run: |
                  cd Backend/
                  npm test
    backend-deploy:
      name: deploy
      runs-on: ubuntu-latest
      needs: backend-compile-test
      steps:
        - name: Checkout
          uses: actions/Checkout@v4
        - name: deploy
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: ${{ secrets.SSH_USERNAME }}
            server: ${{ secrets.SSH_HOST }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            local_path: "./Backend/*"
            remote_path: "./area-anastasia/"
            sftpArgs: "-o ConnectTimeout=5"
        - name: restart api
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl restart api-anastasia.service